---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conformance-test-data
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: stage-conformance-test-data
spec:
  template:
    spec:
      containers:
      - name: stage-conformance-test-data
        image: alpine:3.10
        command:
        - "sh"
        - "-c"
        - "mkdir /conformance;cd /conformance; wget ${CONFORMANCE_TESTS_ARCHIVE}; unzip 1.0.1.zip; rm 1.0.1.zip; chmod -R a+rx /conformance; ls -l /conformance/"
        env:
        - name: CONFORMANCE_TESTS_ARCHIVE
          value: "https://github.com/common-workflow-language/common-workflow-language/archive/v1.0.1.zip"
        volumeMounts:
        - mountPath: /conformance
          name: conformance-test-data
      restartPolicy: Never
      volumes:
      - name: conformance-test-data
        persistentVolumeClaim:
          claimName: conformance-test-data
  backOffLimit: 0
