apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: # namespace here
  name: pod-reader
rules:
- apiGroups: ["", "batch", '\'] # "" indicates the core API group
  resources: ["pods", "jobs"]
  verbs: ["get", "watch", "list", "apply", "create", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: read-pods
  namespace: # namespace here
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: default
  namespace: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: pod-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io