apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: python
    namespace: calrissian
  spec:
    lookupPolicy:
      local: false
    tags:
      - from:
          kind: DockerImage
          name: 'python:3.6'
        name: '3.6'
        referencePolicy:
          type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: calrissian
    name: calrissian
  spec:
    lookupPolicy:
      local: true
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: calrissian
    name: calrissian
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: calrissian:latest
    postCommit: {}
    resources: {}
    source:
      git:
        ref: 599d5aa322abdd6cd4cd5246f2fc590e652f5736
        uri: https://github.com/Duke-GCB/calrissian.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.6
          namespace: calrissian
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
kind: List
metadata: {}
