apiVersion: batch/v1
kind: Job
metadata:
  name: stage-input-data
spec:
  template:
    spec:
      containers:
      - name: stage-input-data
        image: calrissian:latest
        command:
        - "sh"
        - "-c"
        - "cp input-data/* /calrissian/input-data/"
        volumeMounts:
        - mountPath: /calrissian/input-data
          name: calrissian-input-data
      restartPolicy: OnFailure
      volumes:
      - name: calrissian-input-data
        persistentVolumeClaim:
          claimName: calrissian-input-data
